spring:
    cloud:
        stream:
            instanceIndex: 1
            instanceCount: 2
            bindings:
                UserChangedChannel:
                    destination:  UserChangedTopic2
                    content-type: application/json
                    group: userConsumerGroup1
                    consumer:
                        partitioned: true
                        instanceIndex: 1
                        instanceCount: 2
            kafka:
                binder:
                    brokers: localhost:9092
